name: daily-pipeline

on:
  schedule:
    - cron: "0 11 * * *"  # 每天 UTC 11:00（北京时间 19:00）
  workflow_dispatch: {}    # 手动运行

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scrape
        run: python scripts/scrape.py

      - name: Load to Snowflake
        run: python scripts/load_to_snowflake.py

      - name: Run transform
        run: python scripts/run_transform.py
